name: buffet_mirror
description: App espejo Android (offline-first) para BuffetApp.
publish_to: 'none'
version: 1.0.2+3

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.3.3
  path_provider: ^2.1.3
  path: ^1.9.0
  uuid: ^4.5.1
  provider: ^6.1.2
  share_plus: ^10.0.2
  intl: ^0.19.0
  # Impresión PREVIEW (luego podemos agregar printing/pdf si lo preferís)
  printing: ^5.13.3
  pdf: ^3.11.1
  shared_preferences: ^2.3.2
  package_info_plus: ^8.0.2
  image_picker: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/sql/
    - assets/sync/

flutter_launcher_icons:
  android: true
  ios: false
  image_path: assets/icons/app_icon_foreground.png
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: assets/icons/app_icon_foreground.png
